Novos exercicios ts
sogradesce/Mentoria-PicPay pull request #13
Opened 2022-11-17 14:29 UTC by sogradesce

Confesso que apanhei bastante do LeetCode

criei uma lista sobre vagas conforme conversa com o Gui, e separei algo que possa ser mais fácil de eu trabalhar em cima.

Aceito recomendações do que podemos tratar, posterior a claro o cronograma, segue este exercício do Gui como boas práticas ao mercado de trabalho.

2022-11-17 17:04 UTC, franciscobonand requested changes
Boa mano, a ideia é continuar abrindo PRs como esse para os exercícios restantes também. Caso fique com dúvida em algum deles, pode escrever um comentário dentro do arquivo do exercício que te dou um help comentando no PR.  

Só lembrando de duas coisas:
- Colocar nomes significativos nas pastas e arquivos, para ficar mais fácil de entender o que é só de bater o olho (ex: "exercicio-Guilherme" não deixa claro do que se trata, e "chicoExercicio..." poderia ser "leetcode_...").
- Depois de terminar o desenvolvimento de algo novo, executar `yarn prettier` pra deixar tudo formatado no projeto.

2022-11-17 17:04 UTC, franciscobonand commented on src/arrays/chicoExercicio_remove_duplicates_from_sorted_array.ts
> +};
- Um caso que não é tratado nos testes desse exercício é quando o array `nums` é vazio. Se isso fosse passado como entrada, essa função retornará `1`, mas o correto seria `0`.
- É uma boa prática remover partes de código comentadas.
- As variáveis `num1` e `num0` estão sendo inicializadas com o valor `0`, então na primeira iteração do `while` ele compara se `num[0] < num[0]` e isso sempre vai ser falso. Poderia inicializar `let num1 = 1`, dessa forma não faria essa primeira comparação desnecessária e também poderia remover o `if (nums.length === 1) return 1`

2022-11-17 17:04 UTC, franciscobonand commented on src/arrays/chicoExercicio_remove_element.ts
> +   return i + 1;
Uma dica: a função `splice` modifica o array **in-place**, então vc poderia só retornar o tamanho do array que também funcionaria (tira a necessidade de declarar a variável `i` antes do for loop).  
`return nums.length`

2022-11-17 17:04 UTC, franciscobonand commented on docs/exercicio-Guilherme.md
> +Experiência mínima com BackEnd (HTML,CSS,Javascript)
HTML e CSS pra backend é novidade kkkk

2022-11-29 14:22 UTC, sogradesce commented on src/arrays/chicoExercicio_remove_element.ts
> +   return i + 1;
Justo, essa função eu acabei procurando algo que poderia fazer este trabalho também, em meu pensamento, ele era necessário apesar da variável. 

Agora explicando faz mais sentido

2022-11-29 14:23 UTC, sogradesce commented on src/arrays/chicoExercicio_remove_duplicates_from_sorted_array.ts
> +};
Peguei a logica deste caso, este eu fui me baseando por um outro exercício semelhante, e peguei a logica que ele usou no outro, quando fiz o teste deu como aprovado, mas o tempo de execução foi alto comparado a outros resultados.

2022-11-29 14:23 UTC, sogradesce commented on docs/exercicio-Guilherme.md
> +Experiência mínima com BackEnd (HTML,CSS,Javascript)
Este a vaga estava incorreta mesmo, vou anular.

2022-11-29 14:23 UTC, sogradesce commented
Entendido!

2022-11-29 14:24 UTC, merged